
'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Map } from 'lucide-react'; // Changed icon for variety

export function FoliumMapPlaceholder() {
  const foliumMapUrl = "/data/folium_maps/sample_map.html"; // Path to the sample HTML map

  return (
    <Card className="shadow-lg flex-1">
      <CardHeader>
        <CardTitle className="text-xl flex items-center gap-2">
          <Map className="text-primary" /> Detailed Regional Map (Folium)
        </CardTitle>
        <CardDescription>
          Displays a detailed HTML map, typically generated by Folium using SHP files or other geospatial data. 
          HTML files should be placed in the <code>public/data/folium_maps/</code> directory.
        </CardDescription>
      </CardHeader>
      <CardContent className="aspect-[16/9] relative p-0">
        <iframe
          src={foliumMapUrl}
          title="Folium Map"
          width="100%"
          height="100%"
          className="absolute top-0 left-0 w-full h-full border-0 rounded-b-md"
          sandbox="allow-scripts allow-same-origin" // Added sandbox for security, allow-scripts if Folium maps need JS
        />
      </CardContent>
    </Card>
  );
}

